include(${CMAKE_CURRENT_LIST_DIR}/blogic/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/contract/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/control/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/data/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/database/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/network/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/widgets_dynamic/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/widgets_generative/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/widgets_static/sources.cmake)

set(UNITER_SOURCES
    ${UNITER_BLOGIC_SOURCES}
    ${UNITER_CONTRACT_SOURCES}
    ${UNITER_CONTROL_SOURCES}
    ${UNITER_DATA_SOURCES}
    ${UNITER_DATABASE_SOURCES}
    ${UNITER_NETWORK_SOURCES}
    ${UNITER_WIDGETS_CONTROLLERS_SOURCES}
    ${UNITER_WIDGETS_DYNAMIC_SOURCES}
    ${UNITER_WIDGETS_GENERATIVE_SOURCES}
    ${UNITER_WIDGETS_STATIC_SOURCES}
)
